# Generated by Django 3.2.4 on 2021-07-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xword_data', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clue',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
